In [1]:
import numpy

In [2]:
numpy.__version__

'1.15.1'

In [5]:
import numpy as np

In [6]:
np.__version__

'1.15.1'

In [7]:
L = [i for i in range(10)]

In [8]:
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [9]:
L = [i for i in range(15)]

In [10]:
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

In [11]:
L[5]=100
L

[0, 1, 2, 3, 4, 100, 6, 7, 8, 9, 10, 11, 12, 13, 14]

In [12]:
L[5] = "ML"

In [13]:
L

[0, 1, 2, 3, 4, 'ML', 6, 7, 8, 9, 10, 11, 12, 13, 14]

In [14]:
import array
arr = array.array('i', [i for i in range(10)])

In [15]:
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arr[5] = 'ML'

TypeError: an integer is required (got type str)

In [17]:
arr[5] = 100

In [18]:
arr

array('i', [0, 1, 2, 3, 4, 100, 6, 7, 8, 9])

In [19]:
nparr = np.array([i for i in range(10)])

In [20]:
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
nparr[5]

5

In [23]:
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
nparr.dtype

dtype('int64')

In [26]:
nparr[5] = 5.0

In [27]:
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
nparr2 = np.array([1, 2, 3.0])

In [29]:
nparr2.dtype

dtype('float64')

In [30]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [31]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [32]:
np.full((2,4), 20)

array([[20, 20, 20, 20],
       [20, 20, 20, 20]])

In [33]:
arrange

NameError: name 'arrange' is not defined

Arange

In [34]:
#arange

#arange

In [35]:
np.arrage(0, 20, 2)

AttributeError: module 'numpy' has no attribute 'arrage'

In [36]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [37]:
[i for i in range(0,20,0.2
                 )]

TypeError: 'float' object cannot be interpreted as an integer

In [38]:
np.linspace(0, 20, 11)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [39]:
np.linspace(0, 20, 10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [40]:
random(10)

NameError: name 'random' is not defined

In [41]:
rand(10)

NameError: name 'rand' is not defined

In [42]:
rand(1, 10
    )

NameError: name 'rand' is not defined

In [43]:
rand(1, 20)

NameError: name 'rand' is not defined

In [44]:
math.rand(10)

NameError: name 'math' is not defined

In [45]:
import math

In [46]:
math.rand(10)

AttributeError: module 'math' has no attribute 'rand'

In [47]:
math.random(10)

AttributeError: module 'math' has no attribute 'random'

In [48]:
random()

NameError: name 'random' is not defined

In [49]:
python.version

NameError: name 'python' is not defined

In [50]:
from random import randint

In [51]:
randint(0, 10)

10

In [52]:
randint(0, 10)

6

In [53]:
randint(0, 10)

6

In [54]:
randint(0, 10)

8

In [55]:
randint(0, 10)

9

In [56]:
randint(0, 10)

10

In [57]:
np.random.randint(0, 10, 10)

array([0, 1, 6, 3, 6, 2, 4, 0, 6, 7])

In [58]:
array(4, 8, size=10)

TypeError: 'module' object is not callable

In [59]:
np.random.randint(4, 8, size=10)

array([6, 5, 6, 5, 5, 5, 4, 7, 7, 5])

In [60]:
np.random.randint(4, 8, size=(5,10))

array([[7, 4, 4, 4, 4, 5, 4, 7, 7, 7],
       [7, 5, 6, 4, 7, 5, 7, 4, 7, 5],
       [5, 7, 7, 6, 7, 7, 6, 4, 7, 7],
       [6, 5, 5, 6, 7, 5, 7, 5, 7, 7],
       [7, 5, 5, 4, 5, 4, 5, 5, 7, 4]])

In [61]:
np.random.randint(4, 8, size=(5,10, 2))

array([[[7, 5],
        [4, 5],
        [7, 5],
        [7, 5],
        [4, 6],
        [7, 6],
        [7, 6],
        [6, 5],
        [6, 4],
        [4, 7]],

       [[4, 4],
        [6, 6],
        [4, 7],
        [6, 4],
        [5, 7],
        [5, 6],
        [6, 7],
        [4, 4],
        [7, 6],
        [7, 5]],

       [[5, 6],
        [4, 5],
        [4, 6],
        [7, 4],
        [6, 4],
        [5, 4],
        [7, 4],
        [5, 6],
        [7, 4],
        [6, 6]],

       [[7, 5],
        [4, 4],
        [5, 4],
        [7, 6],
        [6, 7],
        [7, 4],
        [5, 4],
        [7, 6],
        [4, 5],
        [6, 4]],

       [[7, 4],
        [6, 4],
        [6, 7],
        [7, 6],
        [7, 6],
        [7, 7],
        [4, 4],
        [7, 7],
        [5, 7],
        [7, 7]]])

In [62]:
np.random.seed(666)

In [63]:
np.random.randint(4, 8, size=(5,10))

array([[4, 6, 5, 6, 6, 6, 5, 6, 4, 5],
       [7, 6, 7, 4, 7, 4, 6, 5, 7, 4],
       [6, 4, 7, 5, 6, 4, 7, 5, 5, 5],
       [4, 7, 4, 4, 4, 4, 4, 4, 6, 6],
       [6, 7, 4, 5, 4, 6, 5, 6, 7, 5]])

In [64]:
np.random.seed(666)

In [65]:
np.random.randint(4, 8, size=(5,10))

array([[4, 6, 5, 6, 6, 6, 5, 6, 4, 5],
       [7, 6, 7, 4, 7, 4, 6, 5, 7, 4],
       [6, 4, 7, 5, 6, 4, 7, 5, 5, 5],
       [4, 7, 4, 4, 4, 4, 4, 4, 6, 6],
       [6, 7, 4, 5, 4, 6, 5, 6, 7, 5]])

In [66]:
np.random.random((3,2))

array([[0.97834699, 0.53280254],
       [0.25913185, 0.58381262],
       [0.32569065, 0.88889931]])

In [67]:
np.random.normal()

1.1413367715995875

In [68]:
np.random.normal()

0.45243661909618677

In [69]:
np.random.normal()

-2.2349687669162455

In [70]:
np.random.normal()

1.2704776597908876

In [71]:
np.random.normal()

-0.7292882099499053

In [72]:
np.random.normal?

In [73]:
np.random?

In [74]:
help(np.random.normal)

Help on built-in function normal:

normal(...) method of mtrand.RandomState instance
    normal(loc=0.0, scale=1.0, size=None)
    
    Draw random samples from a normal (Gaussian) distribution.
    
    The probability density function of the normal distribution, first
    derived by De Moivre and 200 years later by both Gauss and Laplace
    independently [2]_, is often called the bell curve because of
    its characteristic shape (see the example below).
    
    The normal distributions occurs often in nature.  For example, it
    describes the commonly occurring distribution of samples influenced
    by a large number of tiny, random disturbances, each with its own
    unique distribution [2]_.
    
    Parameters
    ----------
    loc : float or array_like of floats
        Mean ("centre") of the distribution.
    scale : float or array_like of floats
        Standard deviation (spread or "width") of the distribution.
    size : int or tuple of ints, optional
        Output shap