# 测试我们的算法

In [7]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets
iris = datasets.load_iris()
X = iris.data
y = iris.target

In [3]:
X.shape

(150, 4)

In [5]:
y.shape

(150,)

### train test split

In [15]:
# 需要注意的几个问题：
# 不能简单的在数据集上分离出一小部分，需要用 shuffle
# 而且这个 shuffle 需要同时用到 X 和 y 上
shuffle_indexes = np.random.permutation(len(X))
print(shuffle_indexes)

test_ratio = 0.2
test_size = int(len(X) * test_ratio)
print("test_size > ", test_size)

test_indexes = shuffle_indexes[:test_size]
train_indexes = shuffle_indexes[test_size:]

X_train = X[train_indexes]
y_train = y[train_indexes]
X_test = X[test_indexes]
y_test = y[test_indexes]

print(X_train)
print(y_train)
print(X_test)
print(y_test)

[ 84  37  65 109  62 116  19 138  77   6  92 101  11  41  24 123 148 130
  90   0  16 139  12  94  50  43   2  91 143  31  72 147  70 142  44 117
  69  54  13 121 129  89  38 134  68  10  36   5  48  78  45   9  95  73
  52 103 133  60  20 100 104 111  88  66  17  32  47 119 127  39 102  21
   1 146 118  34  87  51 107  53  42  14 149 125  76 137  61 135 120  63
 140  59  74  33 126 122 124  67  55  58  75 110 105  81  56  86  29  80
  18  64  46  71  26  25   4  35  83 128 113  22  23  40  98  49  97   8
  93 106  57  96  28  82  30 132 144  79   3 114  15 141  27 115 145 108
   7  85  99 112 136 131]
test_size >  30
[[6.3 2.5 4.9 1.5]
 [6.5 3.  5.2 2. ]
 [5.9 3.2 4.8 1.8]
 [5.8 2.7 5.1 1.9]
 [5.1 3.8 1.9 0.4]
 [7.7 3.8 6.7 2.2]
 [5.6 2.5 3.9 1.1]
 [6.5 2.8 4.6 1.5]
 [4.3 3.  1.1 0.1]
 [5.6 2.8 4.9 2. ]
 [7.2 3.  5.8 1.6]
 [5.5 2.5 4.  1.3]
 [4.4 3.  1.3 0.2]
 [6.1 2.6 5.6 1.4]
 [6.2 2.2 4.5 1.5]
 [5.4 3.7 1.5 0.2]
 [5.5 3.5 1.3 0.2]
 [5.4 3.9 1.7 0.4]
 [5.3 3.7 1.5 0.2]
 [6.  2.9 4.5

In [19]:
from playML.model_selection import train_test_split

In [21]:
X_train, x_test, y_train, y_test = train_test_split(X, y)

In [23]:
X_train.shape

(120, 4)

In [24]:
x_test.shape

(30, 4)

In [25]:
y_train.shape

(120,)

In [26]:
y_test.shape

(30,)

In [32]:
from playML.kNN import KNNClassifier
kNNClassifier = KNNClassifier(6)
kNNClassifier.fit(X_train, y_train)
y_predict = kNNClassifier.predict(x_test)

In [34]:
predict("算法准确率", sum(y_predict == y_test)/len(y_test))

1.0

# 使用 sklean 中的 train_test_split

In [ ]:
from sklearn.model_selection import train_test_split

In [45]:
X_train, x_test, y_train, y_test = train_test_split(X, y)
print(X_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(120, 4)
(30, 4)
(120,)
(30,)


In [43]:
import sklearn as sklearn
print(sklearn.__version__)

0.19.2
