In [26]:
# 合并操作
import numpy as np
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
print("x > ", x)
print("y > ", y)
print("============")

# 合并
z = np.concatenate([x, y])
print("z > ", z)
print("============")

A = np.array([[1, 2, 3], [4, 5, 6]])
print("A > ", A)
print("============")

# Default axis=0, 就是拼接到第一个维度上面
print("A.A > ", np.concatenate([A, A]))
print("============")

# 拼接到第二个维度上
print("A+A > ", np.concatenate([A, A], axis=1))
print("============")

# 现在 A 是一个 2*3 的多维数组，x 是 3*1 的向量，转置 x 之后可以连接他们
print("A.x > ", np.concatenate([A, x.reshape(1, -1)]))
print("============")

# vstack 纵向拼接，相比前面的转置之后拼接的方法容错性更好
np.vstack([A, x])

# hstack 横向拼接
B = np.full((2, 2), 100)
print("B > ", B)
np.hstack([B, B])

x >  [1 2 3]
y >  [3 2 1]
z >  [1 2 3 3 2 1]
A >  [[1 2 3]
 [4 5 6]]
A.A >  [[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
A+A >  [[1 2 3 1 2 3]
 [4 5 6 4 5 6]]
A.x >  [[1 2 3]
 [4 5 6]
 [1 2 3]]
B >  [[100 100]
 [100 100]]


array([[100, 100, 100, 100],
       [100, 100, 100, 100]])

# 分割操作

In [44]:
x = np.arange(10)
print("x > ", x)

# 分割点可以是多个数字，代表切割的各个分段点
x1, x2, x3 = np.split(x, [3,7])
print("x1 > ", x1)
print("x2 > ", x2)
print("x3 > ", x3)

A = np.arange(16).reshape([4, 4])
print("A > ", A)

A1, A2 = np.split(A, [2])
print("A1 > ", A1)
print("A2 > ", A2)

A1, A2 = np.split(A, [2], axis=1)
print("A1 > ", A1)
print("A2 > ", A2)

upper, lower = np.vsplit(A, [2])
print("upper > ", upper)
print("lower > ", lower)

left, right = np.hsplit(A, [2])
print("left > ", left)
print("right > ", right)

# 这个例子在机器学习中经常使用，比如我们的数据集，前三个列是输入，最后一列是 label, 这样切分之后可以得到 X 和 y
X, y = np.hsplit(A, [-1])
print("X > ", X)
print("y > ", y)
print("y 转为向量", y[:, 0])

x >  [0 1 2 3 4 5 6 7 8 9]
x1 >  [0 1 2]
x2 >  [3 4 5 6]
x3 >  [7 8 9]
A >  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
A1 >  [[0 1 2 3]
 [4 5 6 7]]
A2 >  [[ 8  9 10 11]
 [12 13 14 15]]
A1 >  [[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
A2 >  [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
upper >  [[0 1 2 3]
 [4 5 6 7]]
lower >  [[ 8  9 10 11]
 [12 13 14 15]]
left >  [[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
right >  [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
X >  [[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]]
y >  [[ 3]
 [ 7]
 [11]
 [15]]
y 转为向量 [ 3  7 11 15]


# 开始于 numpy 的矩阵运算